---
- name: ensure mosh package
  include_role:
    name: "damex.package"
  vars:
    package_packages:
      - name: "{{ mosh_package_name }}"
        version: "{{ mosh_package_version }}"
        state: "{{ mosh_package_state }}"
